[package]
name = "password_manager"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
iced = { version = "0.13.1", features = ["canvas"] }
serde = { version = "1.0.228", features = ["derive"] }
